# Generated by Django 2.1.3 on 2019-06-28 03:41

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pic',
            field=models.ImageField(blank=True, upload_to='picFolder/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100, validators=[myapp.validators.validate_product_stock]),
        ),
    ]
