# Generated by Django 2.1.3 on 2019-06-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190628_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pic',
            new_name='userImage',
        ),
    ]
